package net.nemerosa.jenkins.seed.config;

import lombok.Data;

@Data
public class EventStrategyConfig {

    /**
     * Defines the way a pipeline is managed in case a deletion event is fired. If yes (default), the
     * entire pipeline is deleted (the complete branch folder). If no, only the branch seed job is
     * deleted but the rest of the pipeline remains intact.
     */
    private boolean delete = true;

    /**
     * When a Seed event is received (update of the pipeline definition), defines the behaviour to adopt.
     * If yes (default), regenerate the pipeline. If no, do not regenerate the pipeline.
     */
    private boolean auto = true;

    /**
     * When a commit event is received (commit, push), defines the behaviour to adopt. If yes (default),
     * triggers the pipeline. If no, does not trigger the pipeline.
     */
    private boolean trigger = true;

    /**
     * When a comment event is received, defines the parameter which contains the revision/commit to build.
     */
    private String commit = "COMMIT";

    /**
     * Property which defines if the pipeline must be started after it has been generated or regenerated. If
     * yes (default), the pipeline is started after generation. If no, it's not started. Note that changing
     * this property needs the branch seed to be regenerated by the branch generator.
     */
    private boolean startAuto = true;

}
